module EBU
  # Limit upload size for individual file uploads.
  UPLOAD_MAX_SIZE = 256.megabytes
  
  # Timeout setting for communicating with transcoders (in seconds).
  TRANSCODER_TIMEOUT = 5
  
  # Base location for intermediate files generated by ffmpeg / Codem.
  INTERMEDIATE_FILE_LOCATION = [Rails.root, 'tmp', 'intermediate'].join(File::SEPARATOR)
  
  # Callback URL for Codem transcoder. Depends on Rails environment and setup.
  CALLBACK_URL_FOR_CODEM = case Rails.env
    when 'development' then 'http://localhost:3000/codem_notifications'
    else ''
  end
  
  #ALLOWED_CONTENT_TYPES = /\Aimage|\Avideo|\Atext/
end