json.template_tag     SecureRandom.hex(8)
json.json_only        false
json.no_template      false
json.only_logged_user true
json.only_member_user false
json.only_admin_user  false
json.cache_time       0
json.cache_by_user    false
json.user_info        ["username"]